name: Sample Workflow
on:
  push: # enabling push event on main branch to fire the workflow
    branches:
      - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout out current code using public action
        uses: actions/checkout@v2
      - name: print current files
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -a

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: print some text
        run: echo 'Hello world'
