name: Sample Workflow
on:
  push: # enabling push event on main branch to fire the workflow
    branches:
      - main


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: print current files
        run: | # this | enables us to multiple commands, good for formatting
          pwd
          ls -aR


  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - name: print outer files # this steps won't be showing any files as we didn't checkout our codes
        run: |
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          cd ..
          pwd
          ls -a
          cd ..



  job3:
    runs-on: ubuntu-latest
    needs: [job2]
    steps:
      - name: print env variables
        run: echo $VAR1 $VAR2 $VAR3
        env:
          VAR1: Thank you
          VAR2: very much.
          VAR3: Enjoy !!!
