name: Scheduled
on:
  schedule:
    - cron: "*/10 * * * *"


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: greet
        run: | # this | enables us to multiple commands, good for formatting
          echo 'Hello mate'
